# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('u', 'Not Approved'), ('a', 'Approved'), ('r', 'Rejectd')], default='Not Approved', max_length=1),
        ),
    ]
